name=input("Enter Name: ")
regno=input("Enter Registraion Number: ")
age=int(input("Enter age: "))
branch=input("Enter Your Branch: ")
email=input("Enter Your Emai id: ")
print("Hi! ",name,"\nNice meeting you\n")
print("Your Details are: ")
print("Registraion Number: ",regno,"\nage: ",age,"\nbranch: ",branch,"\nemail: ",email)